version: '3'

services:
  msgf-bpm-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      # Configuración para tu aplicación Spring Boot
      SPRING_DATASOURCE_URL: ${DB_HOSTNAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver